# Generated by Django 3.2.5 on 2021-07-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
