# Generated by Django 3.2.5 on 2021-07-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matches_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
