# Generated by Django 3.2.5 on 2021-07-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matches_match_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_number',
            field=models.CharField(max_length=254),
        ),
    ]
